global:
  scrape_interval: 15s
  scrape_timeout: 15s

rule_files:

scrape_configs:

  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'Pixel-metrics'
    static_configs:
      - targets: ['host.docker.internal:5001']

  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
        